### ISSUE TITLE
Wireframe

### ISSUE THREAD

**Issue by Jin-s-work** [WinterSpringProject/PROJECT-GLFP-FE#2]
- 서비스는 일단 서강대학교 학생들을 대상으로 진행하려 합니다.
- 대략적인 Web application 구성을 Valsamiq으로 그려보았습니다.

**Comment by Jin-s-work** [comment]
- 메인 화면(처음 접속 상태)
<img width="826" alt="스크린샷 2021-02-04 오후 8 49 02" src="https://user-images.githubusercontent.com/61958748/106889064-d41eae80-672a-11eb-8f91-3a3aa44e29f2.png">

- 회원 가입 창
<img width="1002" alt="스크린샷 2021-02-04 오후 8 49 16" src="https://user-images.githubusercontent.com/61958748/106889074-d7199f00-672a-11eb-8ccb-2fe5e05da6ea.png">

- 로그인 화면 창
<img width="1002" alt="스크린샷 2021-02-04 오후 8 49 20" src="https://user-images.githubusercontent.com/61958748/106889080-da148f80-672a-11eb-9fa4-77d295559b99.png">

- 1:1 채팅 만들기
<img width="582" alt="스크린샷 2021-02-04 오후 8 49 50" src="https://user-images.githubusercontent.com/61958748/106889086-ded94380-672a-11eb-9575-249809b46ef3.png">

- 1:1 채팅 요청
<img width="940" alt="스크린샷 2021-02-04 오후 8 50 07" src="https://user-images.githubusercontent.com/61958748/106889094-e3056100-672a-11eb-9574-2b9c29097bb4.png">

- 1:1 채팅 요청 내역 확인
<img width="964" alt="스크린샷 2021-02-04 오후 8 50 16" src="https://user-images.githubusercontent.com/61958748/106889107-e698e800-672a-11eb-8694-80c25a32e407.png">

- 메인 화면(로그인 상태)
<img width="1038" alt="스크린샷 2021-02-04 오후 8 50 24" src="https://user-images.githubusercontent.com/61958748/106889118-e993d880-672a-11eb-8aef-fd04ff10b612.png">

- 마이페이지
<img width="877" alt="스크린샷 2021-02-04 오후 8 50 37" src="https://user-images.githubusercontent.com/61958748/106889127-edbff600-672a-11eb-9879-b6bbf8920ebb.png">

- 1:1 채팅방
<img width="822" alt="스크린샷 2021-02-04 오후 8 51 08" src="https://user-images.githubusercontent.com/61958748/106889148-f57f9a80-672a-11eb-8c87-c2f1246bbd89.png">

- 게임 친구 구하는 게시판
<img width="1055" alt="스크린샷 2021-02-04 오후 8 51 22" src="https://user-images.githubusercontent.com/61958748/106889157-fa444e80-672a-11eb-9425-48321f62c6f4.png">

**Comment by Jin-s-work** [comment]
다음과 같이 만들어보았는데, 디테일적인 부분은 진행하면서 추가해나가려고 합니다.

**Comment by gyumnnii** [comment]
안녕하세요.

UI 디자인은 깔끔하게 잘 해주셨는데 의견 하나 드리겠습니다.

와이어 프레임으로 UI/UX 디자인을 할 때는
페이지에 따른 UI만 작성하는 것이 아니라
전체적인 페이지의 시나리오를 작성하는 것이 좀 더 좋습니다.

또한 애니메이션 등 각 컴포넌트의 동작이 함께 정의된다면
바로 개발에 착수할 수 있어서 좀 더 좋은 효율을 낼 수 있습니다.

와이어 프레임 설계 단계는 일명 "스펙 잡기" 과정이므로
해당 설계를 완료하고 개발에 들어가시는 것을 추천 합니다.
개발 하면서 수정해나가는 방향은 주먹구구식으로 추천드리지 않습니다.

**Comment by Jin-s-work** [comment]
소중한 의견 감사드립니다.
안그래도 코딩을 해 나가는 과정에 있어서 순서를 고려중에 있었는데,
다시 저 부분에서 시나리오를 작성해본 후에 차근차근 해나가는게 저도 좋을 거 같네요.
다시 한번 감사드립니다!
