### ISSUE TITLE
PR, 코드 리뷰 관련 의견

### ISSUE THREAD

**Issue by gyumnnii** [WinterSpringProject/PROJECT-GLFP-FE#8]
PR 올라온 것들이 리뷰 이후 수정 없이 머지 되고 있네요
이와 관련해서 몇 가지 의견 드릴게요

PR 시나리오는 다음과 같습니다.
1. 메인 브랜치와 **별도로 개발 브랜치**를 사용하여 기능 개발 단위로 PR을 올림
2. 팀원들에게 **코드 리뷰**를 받음
3. 수정이 필요하다면 수정하고 현재 PR이 올라간 브랜치에 push 하여 수정사항을 반영
4. 팀원들에게 **다시 리뷰 요청**
5. 승인 받은 후 메인 브랜치에 Merge

위의 흐름에서 2,3,4번이 제대로 안 이루어지는 것 같아 살짝 아쉬운 감이 있습니다..
처음에 올린 코드를 리뷰 이후에 그대로 머지하는 것이 아닌 **수정** 이후에 머지해야 합니다

오늘 회의에서 말씀드린 것과 같이 
**branch protection rule을 메인 브랜치에 적용하여 임의로 메인 브랜치에 머지할 수 없게 만들 필요가 있을 것 같습니다**
참조 : https://gardeny.tistory.com/19

![스크린샷 2021-03-01 오후 5 32 48](https://user-images.githubusercontent.com/49565544/109471535-3cf01100-7ab4-11eb-9f36-fc7493da19b6.png)
현재 메인 브랜치에 올라간 코드입니다..
메인 브랜치에는 꼭 정상 구동되는 깨끗한 코드만 머지될 수 있도록 해주세요!

**Comment by Jin-s-work** [comment]
소중한 의견 정말 감사드립니다!
일단 merge button에서 일반 merge를 막아두었습니다.
앞으로는 꼭 리뷰를 받은 후, 수정을 한 후에 push하여 수정한 후 다시 리뷰를 받은 뒤에 merge하도록 하겠습니다.
신경써 주셔서 감사합니다
